version: '2'

services:
    custom_printf:
        build: .
        ports:
            - '20006:5555'
        stdin_open: true
        tty: true
        volumes:
            - ./flag:/flag
            - ./source/custom_printf:/home/ctf/custom_printf
